# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(880, 578)
		MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.Hlayout_main = QtWidgets.QHBoxLayout(self.centralwidget)
		self.Hlayout_main.setObjectName("MainLayout")
		self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
		self.tabWidget.setGeometry(QtCore.QRect(10, 10, 861, 521))
		self.tabWidget.setObjectName("tabWidget")
		self.tab = QtWidgets.QWidget()
		self.tab.setObjectName("tab")
		self.VLayoutTab0 = QtWidgets.QVBoxLayout(self.tab)
		self.VLayoutTab0.setObjectName("VLayTab0")

		self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
		self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 821, 481))
		self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout()
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.lbe_imgA= QtWidgets.QLabel(self.verticalLayoutWidget)
		self.lbe_imgA.setAutoFillBackground(True)
		self.lbe_imgA.setAlignment(QtCore.Qt.AlignCenter)
		self.lbe_imgA.setObjectName("lbe_imgA")
		self.verticalLayout_2.addWidget(self.lbe_imgA)
		self.btn_selNegBoard = QtWidgets.QPushButton(self.verticalLayoutWidget)
		self.btn_selNegBoard.setAutoDefault(True)
		self.btn_selNegBoard.setDefault(False)
		self.btn_selNegBoard.setFlat(False)
		self.btn_selNegBoard.setObjectName("btn_selNegBoard")
		self.verticalLayout_2.addWidget(self.btn_selNegBoard)
		self.horizontalLayout.addLayout(self.verticalLayout_2)
		self.verticalLayout_3 = QtWidgets.QVBoxLayout()
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.lbe_imgB = QtWidgets.QLabel(self.verticalLayoutWidget)
		self.lbe_imgB.setAutoFillBackground(True)
		self.lbe_imgB.setAlignment(QtCore.Qt.AlignCenter)
		self.lbe_imgB.setObjectName("lbe_imgB")
		self.verticalLayout_3.addWidget(self.lbe_imgB)
		self.btn_selOkBoard = QtWidgets.QPushButton(self.verticalLayoutWidget)
		self.btn_selOkBoard.setAutoFillBackground(False)
		self.btn_selOkBoard.setAutoDefault(False)
		self.btn_selOkBoard.setObjectName("btn_selOkBoard")
		self.verticalLayout_3.addWidget(self.btn_selOkBoard)
		self.horizontalLayout.addLayout(self.verticalLayout_3)
		self.verticalLayout.addLayout(self.horizontalLayout)
		self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
		self.progressBar.setProperty("value", 0)
		self.progressBar.setObjectName("progressBar")
		self.verticalLayout.addWidget(self.progressBar)
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_2.addItem(spacerItem)
		self.btn_upload = QtWidgets.QPushButton(self.verticalLayoutWidget)
		self.btn_upload.setObjectName("btn_upload")
		self.horizontalLayout_2.addWidget(self.btn_upload)
		self.btn_startDetect = QtWidgets.QPushButton(self.verticalLayoutWidget)
		self.btn_startDetect.setObjectName("btn_startDetect")
		self.horizontalLayout_2.addWidget(self.btn_startDetect)
		spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_2.addItem(spacerItem1)
		self.verticalLayout.addLayout(self.horizontalLayout_2)
		self.verticalLayout.setStretch(0, 1)
		self.tabWidget.addTab(self.tab, "")
		self.tab_2 = QtWidgets.QWidget()
		self.tab_2.setObjectName("tab_2")
		self.VLayoutTab1 = QtWidgets.QVBoxLayout(self.tab_2)
		self.VLayoutTab1.setObjectName("VLayTab1")

		#展示页
		self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
		self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 10, 821, 481))
		self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
		self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.lbe_defectCount = QtWidgets.QLabel(self.verticalLayoutWidget_4)
		self.lbe_defectCount.setTextFormat(QtCore.Qt.AutoText)
		self.lbe_defectCount.setScaledContents(False)
		self.lbe_defectCount.setAlignment(QtCore.Qt.AlignCenter)
		self.lbe_defectCount.setWordWrap(False)
		self.lbe_defectCount.setObjectName("lbe_defectCount")
		self.verticalLayout_4.addWidget(self.lbe_defectCount)
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		#按钮行
		#屏蔽边缘缺陷
		self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
		self.label_4.setObjectName("label_4")
		self.horizontalLayout_3.addWidget(self.label_4)
		self.btn_edge_yes = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
		self.btn_edge_yes.setObjectName("btn_edge_yes")
		self.horizontalLayout_3.addWidget(self.btn_edge_yes)
		self.btn_edge_no = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
		self.btn_edge_no .setObjectName("btn_edge_no")
		self.horizontalLayout_3.addWidget(self.btn_edge_no)
		#缺陷等级
		self.lbe_level = QtWidgets.QLabel(self.verticalLayoutWidget_4)
		self.lbe_level.setObjectName("label_level")
		self.horizontalLayout_3.addWidget(self.lbe_level)
		self.btn_level_1= QtWidgets.QPushButton(self.verticalLayoutWidget_4)
		self.btn_level_1.setObjectName("btn_l1")
		self.horizontalLayout_3.addWidget(self.btn_level_1)
		self.btn_level_2= QtWidgets.QPushButton(self.verticalLayoutWidget_4)
		self.btn_level_2.setObjectName("btn_l2")
		self.horizontalLayout_3.addWidget(self.btn_level_2)
		self.btn_level_3= QtWidgets.QPushButton(self.verticalLayoutWidget_4)
		self.btn_level_3.setObjectName("btn_l3")
		self.horizontalLayout_3.addWidget(self.btn_level_3)
		#视图模式
		self.lbe_show = QtWidgets.QLabel(self.verticalLayoutWidget_4)
		self.lbe_show.setObjectName("label_show")
		self.horizontalLayout_3.addWidget(self.lbe_show)
		self.btn_show_1= QtWidgets.QPushButton(self.verticalLayoutWidget_4)
		self.btn_show_1.setObjectName("btn_show_1")
		self.horizontalLayout_3.addWidget(self.btn_show_1)
		self.btn_show_2= QtWidgets.QPushButton(self.verticalLayoutWidget_4)
		self.btn_show_2.setObjectName("btn_show_2")
		self.horizontalLayout_3.addWidget(self.btn_show_2)
		self.btn_show_3= QtWidgets.QPushButton(self.verticalLayoutWidget_4)
		self.btn_show_3.setObjectName("btn_show_3")
		self.horizontalLayout_3.addWidget(self.btn_show_3)
		#保存
		self.lbe_save = QtWidgets.QLabel(self.verticalLayoutWidget_4)
		self.lbe_save.setObjectName("label_save")
		self.horizontalLayout_3.addWidget(self.lbe_save)

		self.btn_saveRes= QtWidgets.QPushButton(self.verticalLayoutWidget_4)
		self.btn_saveRes.setObjectName("btn_saveRes")
		self.horizontalLayout_3.addWidget(self.btn_saveRes)
		self.verticalLayout_4.addLayout(self.horizontalLayout_3)
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.verticalLayout_5 = QtWidgets.QVBoxLayout()
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.lbe_PatchA = QtWidgets.QLabel(self.verticalLayoutWidget_4)
		self.lbe_PatchA.setAutoFillBackground(True)
		self.lbe_PatchA.setAlignment(QtCore.Qt.AlignCenter)
		self.lbe_PatchA.setObjectName("lbe_PatchA")
		self.verticalLayout_5.addWidget(self.lbe_PatchA)
		self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
		self.label_8.setAlignment(QtCore.Qt.AlignCenter)
		self.label_8.setObjectName("label_8")
		self.verticalLayout_5.addWidget(self.label_8)
		self.verticalLayout_5.setStretch(0, 1)
		self.horizontalLayout_5.addLayout(self.verticalLayout_5)
		self.verticalLayout_6 = QtWidgets.QVBoxLayout()
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.lbe_PatchB = QtWidgets.QLabel(self.verticalLayoutWidget_4)
		self.lbe_PatchB.setAutoFillBackground(True)
		self.lbe_PatchB.setAlignment(QtCore.Qt.AlignCenter)
		self.lbe_PatchB.setObjectName("lbe_PatchB")
		self.verticalLayout_6.addWidget(self.lbe_PatchB)
		self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
		self.label_9.setAlignment(QtCore.Qt.AlignCenter)
		self.label_9.setObjectName("label_9")
		self.verticalLayout_6.addWidget(self.label_9)
		self.verticalLayout_6.setStretch(0, 1)
		self.horizontalLayout_5.addLayout(self.verticalLayout_6)
		self.verticalLayout_4.addLayout(self.horizontalLayout_5)
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_4.addItem(spacerItem2)
		self.btn_enlarge = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
		self.btn_enlarge.setObjectName("btn_enlarge")
		self.horizontalLayout_4.addWidget(self.btn_enlarge)
		self.btn_moveLeft = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
		self.btn_moveLeft.setObjectName("btn_moveLeft")
		self.horizontalLayout_4.addWidget(self.btn_moveLeft)
		self.lbe_indexNow = QtWidgets.QLabel(self.verticalLayoutWidget_4)
		self.lbe_indexNow.setObjectName("lbe_indexNow")
		self.horizontalLayout_4.addWidget(self.lbe_indexNow)
		self.btn_moveRight = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
		self.btn_moveRight.setObjectName("btn_moveRight")
		self.horizontalLayout_4.addWidget(self.btn_moveRight)
		self.btn_shrink = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
		self.btn_shrink.setObjectName("btn_shrink")
		self.horizontalLayout_4.addWidget(self.btn_shrink)
		spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_4.addItem(spacerItem3)
		self.verticalLayout_4.addLayout(self.horizontalLayout_4)
		self.verticalLayout_4.setStretch(2, 1)
		self.tabWidget.addTab(self.tab_2, "")
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 22))
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)
		self.Hlayout_main.addWidget(self.tabWidget)
		self.VLayoutTab0.addWidget(self.verticalLayoutWidget)
		self.VLayoutTab1.addWidget(self.verticalLayoutWidget_4)

		self.horizontalLayout_5.setStretch(1,1)
		self.horizontalLayout_5.setStretch(0,1)
		self.horizontalLayout.setStretch(0,1)
		self.horizontalLayout.setStretch(1,1)
		
		self.retranslateUi(MainWindow)
		self.tabWidget.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)
	

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "PCB缺陷检测展示系统"))
		self.lbe_imgA.setText(_translate("MainWindow", "ImgA"))
		self.btn_selNegBoard.setText(_translate("MainWindow", "选择待测试板"))
		self.lbe_imgB.setText(_translate("MainWindow", "lbe_imgB"))
		self.btn_selOkBoard.setText(_translate("MainWindow", "选择标准板"))
		self.btn_upload.setText(_translate("MainWindow", "上传数据"))
		self.btn_startDetect.setText(_translate("MainWindow", "开始检测"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", " 上传页"))
		self.lbe_defectCount.setText(_translate("MainWindow", "结果展示"))

		self.label_4.setText(_translate("MainWindow", "  屏蔽边缘缺陷:"))
		self.btn_edge_yes.setText(_translate("MainWindow", "是"))
		self.btn_edge_no.setText(_translate("MainWindow", "否"))

		self.lbe_level.setText(_translate("MainWindow", "缺陷过滤等级:"))
		self.btn_level_1.setText(_translate("MainWindow", "A"))
		self.btn_level_2.setText(_translate("MainWindow", "B"))
		self.btn_level_3.setText(_translate("MainWindow", "C"))

		self.lbe_show.setText(_translate("MainWindow", "显示模式:"))
		self.btn_show_1.setText(_translate("MainWindow", "统计视图"))
		self.btn_show_2.setText(_translate("MainWindow", "全局视图"))
		self.btn_show_3.setText(_translate("MainWindow", "对比视图"))

		self.lbe_save.setText(_translate("MainWindow", "导出结果:"))

		self.btn_saveRes.setText(_translate("MainWindow", "保存图像"))
		self.lbe_PatchA.setText(_translate("MainWindow", "PatchA"))
		self.label_8.setText(_translate("MainWindow", "待检测板Patch"))
		self.lbe_PatchB.setText(_translate("MainWindow", "PatchB"))
		self.label_9.setText(_translate("MainWindow", "标准板Patch"))
		self.btn_enlarge.setText(_translate("MainWindow","放大"))
		self.btn_moveLeft.setText(_translate("MainWindow", "<"))
		self.lbe_indexNow.setText(_translate("MainWindow", "index / ALL"))
		self.btn_moveRight.setText(_translate("MainWindow", ">"))
		self.btn_shrink.setText(_translate("MainWindow","缩小"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "展示页"))

		self.lbe_imgA.setSizePolicy(QtWidgets.QSizePolicy.Ignored,QtWidgets.QSizePolicy.Ignored)
		self.lbe_imgB.setSizePolicy(QtWidgets.QSizePolicy.Ignored,QtWidgets.QSizePolicy.Ignored)
		self.lbe_PatchA.setSizePolicy(QtWidgets.QSizePolicy.Ignored,QtWidgets.QSizePolicy.Ignored)
		self.lbe_PatchB.setSizePolicy(QtWidgets.QSizePolicy.Ignored,QtWidgets.QSizePolicy.Ignored)
		#self.lbe_imgA.setScaledContents(True)
		#self.lbe_imgB.setScaledContents(True)

